spring:
  application:
    name: ConsumerUser
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 10
      slidingWindowSize: 100
      slidingWindowType: COUNT_BASED
  instances:
    backendA:
      baseConfig: default

